r_label_text_dic = {'label_choose_state': ['功能选择：', 'Function：'],
                    'option_is_cleanfile': ['清理文件', 'Cleanfile'],
                    'option_is_syncfile': ['同步文件', 'Syncfile'],
                    'cf_label_old_path': ['原文件夹路径：', 'original path：'],
                    'cf_browse_old_path_button': ['浏览', 'Browse'],
                    'cf_browse_new_path_button': ['浏览', 'Browse'],
                    'cf_label_new_path': ['目标文件夹路径：', 'Target path：'],
                    'cf_label_move_options': ['文件夹移动选项：', 'Expire Criteria：'],
                    'cf_option_mode_1': ['以项目最后修改时间为过期判断依据', "Files' latest edit time"],
                    'cf_option_mode_2': ['以项目最后访问时间为过期判断依据', "Files' latest ask time"],
                    'cf_option_folder_move': ['移动项目包括文件夹', 'Move items including Folders'],
                    'cf_label_keep_files': ['保留项目(选填)：', 'Reserved Files(opt)：'],
                    'cf_label_keep_formats': ['     保留文件格式(选填)：', 'Reserved Formats(opt)：'],
                    'cf_label_time': ['过期时间设定(小时)：', 'Expire Hours：'],
                    'cf_label_start_options': ['系统选项：', 'Boot option：'],
                    'cf_option_is_auto': ['开机自动运行本存档(若保存)', 'Autorun this config(if saved)'],
                    'sf_label_place_mode': ['路径模式选择：', 'Sync-Path mode：'],
                    'sf_option_mode_usb': ['可移动磁盘(卷)同步模式', 'Removable Volume mode'],
                    'sf_option_mode_local': ['本地文件夹同步模式', 'Local Folder mode'],
                    'sf_label_path_1': [['选择可移动磁盘：', '文件夹路径-A：'], ['Removable Volume', 'Folder Path-A：']],
                    'sf_label_path_2': [['本地文件夹路径：', '文件夹路径-B：'], ['Local Path', 'Folder Path-B：']],
                    'sf_browse_path_1_button': ['浏览', 'Browse'],
                    'sf_browse_path_2_button': ['浏览', 'Browse'],
                    'sf_label_mode': ['             同步模式选择：', 'Sync mode：'],
                    'sf_option_mode_double': ['双向同步（皆保留最新版本）', 'Two-way Sync'],
                    'sf_option_mode_single': ['单向同步（仅从A向B同步）', 'One-way Sync'],
                    'sf_label_autorun': ['系统选项：', 'Boot option：'],
                    'sf_option_autorun': [['可移动磁盘接入后自动按本存档设置同步(若保存)', '开机自动同步'], ['Autorun when Removable Volume inserted', 'Autorun on startup']],

                    'num_warning': ['警告：请在时间设定栏内输入数字',
                                    'Warning: Please enter a number in the time setting field'],
                    'blank_warning': ['警告：请填写所有非选填项目',
                                      'Warning: Please fill all the blanks not optional'],
                    'path_warning': ['警告：请填输入有效路径！（建议使用浏览）',
                                     'Warning: Please input a path that exists (Browse suggested)'],
                    'ini_error': ['错误：配置信息无效，请尽量不要手动更改ini配置文件',
                                  "Error：Config File invalid, please don't edit the config file directly"],
                    'succ_save': [['信息提示', '信息保存成功！'], ['Information prompt', 'Data saved Successfully']],

                    }
