r_label_text_dic = {
    'file_menu': ['文件', 'File'],
    'readfile_menu': ['读取配置文件', 'Read config'],
    'savefile_menu': ['保存', 'Save config'],
    'option_menu': ['选项', 'Option'],
    'autorun_menu': ['开机自动启动本软件', 'Start automatically'],
    'language_menu': ['语言', 'Language'],
    'help_menu': ['帮助', 'Help'],
    'about_menu': ['关于本软件', 'About'],
    'precautions_menu': ['使用前注意事项', 'Precautions before use'],
    'cf_keep_menu': ['保留文件/文件格式选择', 'Keep file/format setting'],
    'cf_expire_menu': ['过期时间设定', 'Expire time setting'],

    'taskbar_setting': ['设置界面', 'Setting Window'],
    'taskbar_exit': ['退出', 'Exit'],

    'label_choose_state': ['功能选择：', 'Function：'],
    'option_is_cleanfile': ['清理文件', 'Cleanfile'],
    'option_is_syncfile': ['同步文件', 'Syncfile'],
    'cf_label_old_path': ['原文件夹路径：', 'original path：'],
    'cf_browse_old_path_button': ['浏览', 'Browse'],
    'cf_browse_new_path_button': ['浏览', 'Browse'],
    'cf_label_new_path': ['目标文件夹路径：', 'Target path：'],
    'cf_label_move_options': ['过期时间判断依据：', 'Expire Criteria：'],
    'cf_option_mode_1': ['项目最后修改时间', "Files' latest edit time"],
    'cf_option_mode_2': ['项目最后访问时间', "Files' latest ask time"],
    'cf_option_folder_move': ['移动项目包括文件夹', 'Move items including Folders'],
    'cf_label_keep_files': ['保留项目(选填)：', 'Reserved Files(opt)：'],
    'cf_label_keep_formats': ['保留文件格式(选填)：', 'Reserved Fmts(opt)：'],
    'cf_label_time': ['过期时间设定(小时)：', 'Expire Hours：'],
    'cf_label_start_options': ['系统选项：', 'Boot option：'],
    'cf_option_is_auto': ['开机自动运行本存档(若保存)', 'Automatically run this config after Startup(if saved)'],
    'sf_label_place_mode': ['路径模式选择：', 'Sync-Path mode：'],
    'sf_option_mode_usb': ['可移动磁盘(卷)同步模式', 'Removable Volume mode'],
    'sf_option_mode_local': ['本地文件夹同步模式', 'Local Folder mode'],
    'sf_label_path_1': [['选择可移动磁盘：', '文件夹路径-A：'], ['Removable Volume：', 'Folder Path-A：']],
    'sf_label_path_2': [['本地文件夹路径：', '文件夹路径-B：'], ['Local Path：', 'Folder Path-B：']],
    'sf_browse_path_1_button': ['浏览', 'Browse'],
    'sf_browse_path_2_button': ['浏览', 'Browse'],
    'sf_label_mode': ['同步模式选择：', 'Sync mode：'],
    'sf_option_mode_double': ['双向同步（皆保留最新版本）', 'Two-way Sync'],
    'sf_option_mode_single': ['单向同步（仅从A向B同步）', 'One-way Sync'],
    'sf_label_autorun': ['系统选项：', 'Boot option：'],
    'sf_option_autorun': [['可移动磁盘接入后自动按本存档设置同步(若保存)', '开机自动同步'], ['Automatically run when this Removable Volume inserted', 'Automatically run this config after Startup(if saved)']],
    'save_button': ['保存', 'Save'],
    'continue_button': ['运行当前配置', 'Run current configuration'],

    'read_name_label': ['     选择存档：', '   Pick a config：'],
    'read_mode_entry': [['清理文件(Cleanfile)', '同步文件(Syncfile)'], ['Cleanfile', 'Syncfile']],
    'del_save_button': ['删除存档', 'Delete'],
    'sure_name_bottom': ['读取存档', 'Read'],

    'ask_name_window': ['设置配置存档名称', "Set Config's Name"],
    'name_label': ['  请输入存档的名称：', "     Enter a name："],
    'sure_name_button': ['确定保存', 'Confirm'],

    'num_warning': ['警告：请在时间设定栏内输入数字',
                    'Warning: Please enter a number in the time setting field'],
    'blank_warning': ['警告：请填写所有非选填项目',
                      'Warning: Please fill all the blanks not optional'],
    'path_warning': ['警告：请填输入有效路径！（建议使用浏览）',
                     'Warning: Please input a path that exists (Browse suggested)'],
    'ini_error': ['错误：配置信息无效，请尽量不要手动更改ini配置文件',
                  "Error：Config File invalid, please don't edit the config file directly"],
    'succ_save': [['信息提示', '信息保存成功！'], ['Information prompt', 'Data saved Successfully']],

    }
